# Quarkus extension descriptor
# This file tells Quarkus which deployment artifact provides the build steps
# for the janitor-quarkus-runtime artifact.
deployment-artifact=io.terapeak:janitor-quarkus-deployment:1.0.0-SNAPSHOT
