quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:devdb
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.hibernate-orm.schema-management.strategy=create
quarkus.hibernate-orm.log.sql=true
quarkus.scheduler.enabled=true