package io.terapeak.janitor.registry;

import io.terapeak.janitor.annotation.Cleanup;
import io.terapeak.janitor.annotation.Cleanups;
import io.terapeak.janitor.config.CleanupConfig;
import io.terapeak.janitor.processor.CleanupIndexProcessor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Enumeration;
import java.util.List;

/**
 * Discovers all {@link CleanupConfig} instances registered by the compile-time
 * annotation processor index ({@code META-INF/janitor/cleanups.index}).
 *
 * <p>The index file is generated by {@link CleanupIndexProcessor}
 * and contains one fully-qualified class name per line. At runtime the registry
 * loads each class, reads its {@link Cleanup} / {@link Cleanups} annotations, and
 * converts them to {@link CleanupConfig} objects.
 *
 * <p>If no index file is found the registry falls back to returning an empty list
 * (useful in test environments where the annotation processor has not run).
 */
public class CleanupRegistry {

    private static final Logger log = LoggerFactory.getLogger(CleanupRegistry.class);
    static final String INDEX_PATH = "META-INF/janitor/cleanups.index";

    private final ClassLoader classLoader;

    public CleanupRegistry() {
        this(Thread.currentThread().getContextClassLoader());
    }

    public CleanupRegistry(ClassLoader classLoader) {
        this.classLoader = classLoader;
    }

    /**
     * Discover and return all enabled {@link CleanupConfig} instances found on the
     * classpath.
     *
     * @return unmodifiable list of resolved configurations
     */
    public List<CleanupConfig> discoverAll() {
        List<String> classNames = readIndex();
        if (classNames.isEmpty()) {
            log.warn("[Cleanup] No cleanup index found at '{}'. "
                    + "Ensure the annotation processor ran during compilation.", INDEX_PATH);
            return Collections.emptyList();
        }

        List<CleanupConfig> configs = new ArrayList<>();
        for (String className : classNames) {
            configs.addAll(loadFromClass(className));
        }

        log.info("[Cleanup] Discovered {} cleanup job(s) from {} annotated class(es).",
                configs.size(), classNames.size());
        return Collections.unmodifiableList(configs);
    }

    // -------------------------------------------------------------------------
    // Index loading
    // -------------------------------------------------------------------------

    private List<String> readIndex() {
        List<String> names = new ArrayList<>();
        try {
            Enumeration<URL> resources = classLoader.getResources(INDEX_PATH);
            while (resources.hasMoreElements()) {
                URL url = resources.nextElement();
                try (InputStream is = url.openStream();
                     BufferedReader reader = new BufferedReader(
                             new InputStreamReader(is, StandardCharsets.UTF_8))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        line = line.trim();
                        if (!line.isEmpty() && !line.startsWith("#")) {
                            names.add(line);
                        }
                    }
                }
            }
        } catch (IOException e) {
            log.error("[Cleanup] Failed to read cleanup index: {}", e.getMessage(), e);
        }
        return names;
    }

    // -------------------------------------------------------------------------
    // Annotation → Config conversion
    // -------------------------------------------------------------------------

    private List<CleanupConfig> loadFromClass(String className) {
        List<CleanupConfig> configs = new ArrayList<>();
        try {
            Class<?> clazz = classLoader.loadClass(className);

            // Repeatable container
            Cleanups container = clazz.getAnnotation(Cleanups.class);
            if (container != null) {
                for (Cleanup cleanup : container.value()) {
                    configs.add(CleanupConfig.from(cleanup));
                }
            }

            // Single annotation (not inside container)
            Cleanup single = clazz.getAnnotation(Cleanup.class);
            if (single != null) {
                configs.add(CleanupConfig.from(single));
            }

        } catch (ClassNotFoundException e) {
            log.error("[Cleanup] Could not load class '{}' from index: {}", className, e.getMessage());
        }
        return configs;
    }
}
