package io.terapeak.janitor.processor;

import com.google.auto.service.AutoService;
import io.terapeak.janitor.annotation.Cleanup;
import io.terapeak.janitor.annotation.Cleanups;

import io.terapeak.janitor.registry.CleanupRegistry;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import javax.tools.FileObject;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashSet;
import java.util.Set;

/**
 * Compile-time annotation processor that writes a resource index file
 * ({@code META-INF/janitor/cleanups.index}) containing the fully-qualified
 * names of all classes (or package-infos) annotated with {@link Cleanup} or
 * {@link Cleanups}.
 *
 * <p>This approach avoids classpath scanning at runtime. The index is read by
 * {@link CleanupRegistry} when the application starts.
 *
 * <p>The processor is registered via {@code META-INF/services/javax.annotation.processing.Processor}
 * (written automatically by {@code @AutoService}).
 */
@AutoService(Processor.class)
@SupportedAnnotationTypes({
        "io.terapeak.cleanup.annotation.Cleanup",
        "io.terapeak.cleanup.annotation.Cleanups"
})
@SupportedSourceVersion(SourceVersion.RELEASE_11)
public class CleanupIndexProcessor extends AbstractProcessor {

    private static final String INDEX_PATH = "META-INF/janitor/cleanups.index";

    private final Set<String> discoveredClasses = new HashSet<>();

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (roundEnv.processingOver()) {
            writeIndex();
            return false;
        }

        for (TypeElement annotation : annotations) {
            for (Element element : roundEnv.getElementsAnnotatedWith(annotation)) {
                String qualifiedName = getQualifiedName(element);
                if (qualifiedName != null) {
                    discoveredClasses.add(qualifiedName);
                    processingEnv.getMessager().printMessage(
                            Diagnostic.Kind.NOTE,
                            "[CleanupProcessor] Registered: " + qualifiedName,
                            element);
                }
            }
        }
        return false;
    }

    private String getQualifiedName(Element element) {
        if (element instanceof TypeElement) {
            return ((TypeElement) element).getQualifiedName().toString();
        }
        // Package annotations
        if (element.getKind().name().equals("PACKAGE")) {
            return element.toString() + ".package-info";
        }
        return null;
    }

    private void writeIndex() {
        if (discoveredClasses.isEmpty()) return;

        try {
            FileObject resource = processingEnv.getFiler().createResource(
                    StandardLocation.CLASS_OUTPUT, "", INDEX_PATH);

            try (PrintWriter writer = new PrintWriter(resource.openWriter())) {
                writer.println("# Generated by CleanupIndexProcessor — do not edit");
                discoveredClasses.stream()
                        .sorted()
                        .forEach(writer::println);
            }

            processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
                    "[CleanupProcessor] Wrote index with " + discoveredClasses.size()
                    + " entr(ies) to " + INDEX_PATH);

        } catch (IOException e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "[CleanupProcessor] Failed to write index: " + e.getMessage());
        }
    }
}
